server:
  port: ${PORT}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
    redis:
      time-to-live: 86400000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
